---
title: "Assignment 1: Data Description"
author: 
  - Charlene R. Ramos
date: "October 30, 2025"

output: 
  pdf_document:
    latex_engine: xelatex
    number_sections: true
    keep_tex: false
    
fontsize: 12pt
geometry: margin=1.5in

header-includes:
  - \usepackage{amsmath, amssymb}
  - \usepackage{booktabs}
  - \usepackage{caption}      
  - \usepackage{float}
  - \usepackage{geometry}    
  - \usepackage{lmodern}     
  - \usepackage{placeins} 
  - \usepackage{setspace}
  - \doublespacing
  - \usepackage{threeparttable}
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \fancyhf{} % clear default header/footer
  - \cfoot{\thepage} % page number on bottom-right
  - \renewcommand{\headrulewidth}{0pt}
---

```{r setup, include=FALSE}
# install.packages(c("kableExtra","knitr","rmarkdown","tidyverse","tinytex","webshot2"))
# tinytex::install_tinytex() 

knitr::opts_chunk$set(echo = TRUE)
```

```{=latex}

\section{Introduction}

\section{Data}

\section{Methodology \& Results}

\subsection{Vector Autoregression and Reduced-Form Impulse Response Function}

\subsection{Bayesian Methods}

\subsection{Stationarity and Structural Breaks}

\section{Conclusion}

\section{References}

```

```{r render, include=FALSE, eval=FALSE}
rmarkdown::render(
  "/Users/charleneramos/Documents/Git/econ220dproject/code/data_description.Rmd",
  output_format = "pdf_document",
  output_dir = "/Users/charleneramos/Documents/Git/econ220dproject/output/"
)
``
